In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/data/insurance.csv")
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
target = "charges"

In [6]:
y = df[target]
X = df.drop(columns=target)
X.head()

age  gender     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [9]:
X_dummy = pd.get_dummies(X, drop_first=True)
X_dummy.head()

age     bmi  children  gender_male  smoker_yes  region_northwest  \
0   19  27.900         0            0           1                 0   
1   18  33.770         1            1           0                 0   
2   28  33.000         3            1           0                 0   
3   33  22.705         0            1           0                 1   
4   32  28.880         0            1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

In [64]:
X_dummy.values

array([[19.  , 27.9 ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [18.  , 33.77,  1.  , ...,  0.  ,  1.  ,  0.  ],
       [28.  , 33.  ,  3.  , ...,  0.  ,  1.  ,  0.  ],
       ...,
       [18.  , 36.85,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [21.  , 25.8 ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [61.  , 29.07,  0.  , ...,  1.  ,  0.  ,  0.  ]])

In [65]:
type(X_dummy.values)

numpy.ndarray

In [66]:
X_dummy.values.dtype

dtype('float64')

In [69]:
X_dummy.values.astype("float16").dtype

dtype('float16')

In [12]:
from sklearn import model_selection

In [63]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_dummy.values, y
                                        , test_size = 0.3, random_state = 1)

In [13]:
import numpy as np

In [59]:
np.random.seed(123)
(np.random.random(5) * 20).astype("int")

array([13,  5,  4, 11, 14])

In [10]:
from sklearn import preprocessing

In [11]:
scaler = preprocessing.StandardScaler()

In [109]:
scaler.fit(X_train) 

# calcultes x_mean, x_std for each column for calculating z-score.
# z = (x - x_mean)/x_std for each column
# z values will have 0 mean and 1 std deviation for all columns

StandardScaler(copy=True, with_mean=True, with_std=True)

In [73]:
X_train_std = scaler.transform(X_train) # calculates z scores for each column

In [76]:
pd.DataFrame(X_train_std).head()

0         1         2         3         4         5         6  \
0  0.797152 -0.702114 -0.904002  0.976766 -0.509664  1.788102 -0.600387   
1 -1.271085 -0.703758 -0.085679 -1.023787 -0.509664 -0.559252 -0.600387   
2 -0.985811 -0.733340 -0.904002  0.976766 -0.509664 -0.559252 -0.600387   
3  0.797152 -0.414510  1.550967 -1.023787 -0.509664 -0.559252  1.665591   
4  0.868471  1.482037 -0.085679  0.976766 -0.509664 -0.559252 -0.600387   

          7  
0 -0.587220  
1  1.702939  
2 -0.587220  
3 -0.587220  
4  1.702939

In [77]:
pd.DataFrame(X_train_std).describe()

0             1             2             3             4  \
count  9.360000e+02  9.360000e+02  9.360000e+02  9.360000e+02  9.360000e+02   
mean  -9.014631e-17  3.054122e-15 -1.869795e-16 -1.119712e-16  1.775645e-16   
std    1.000535e+00  1.000535e+00  1.000535e+00  1.000535e+00  1.000535e+00   
min   -1.485041e+00 -2.419524e+00 -9.040023e-01 -1.023787e+00 -5.096643e-01   
25%   -9.144925e-01 -7.247116e-01 -9.040023e-01 -1.023787e+00 -5.096643e-01   
50%   -5.867016e-02 -3.076297e-02 -8.567913e-02  9.767656e-01 -5.096643e-01   
75%    8.684707e-01  6.631857e-01  7.326440e-01  9.767656e-01 -5.096643e-01   
max    1.795612e+00  3.689196e+00  3.187613e+00  9.767656e-01  1.962076e+00   

                  5             6             7  
count  9.360000e+02  9.360000e+02  9.360000e+02  
mean   1.560955e-16  1.518254e-17  2.436323e-16  
std    1.000535e+00  1.000535e+00  1.000535e+00  
min   -5.592522e-01 -6.003875e-01 -5.872202e-01  
25%   -5.592522e-01 -6.003875e-01 -5.872202e-01  
50%   -5.592522e-01 -6.003875e-01 -5.872202e-01  
75%   -5.592522e-01  1.665591e+00  1.702939e+00  
max    1.788102e+00  1.665591e+00  1.702939e+00

In [98]:
scaler.mean_

array([38.82264957, 30.68218483,  1.10470085,  0.51175214,  0.20619658,
        0.23824786,  0.26495726,  0.25641026])

In [99]:
scaler.var_

array([1.96605299e+02, 3.70241105e+01, 1.49331124e+00, 2.49861887e-01,
       1.63679551e-01, 1.81485819e-01, 1.94754913e-01, 1.90664037e-01])

In [100]:
pd.DataFrame(X_train).describe()

0           1           2           3           4           5  \
count  936.000000  936.000000  936.000000  936.000000  936.000000  936.000000   
mean    38.822650   30.682185    1.104701    0.511752    0.206197    0.238248   
std     14.029097    6.087997    1.222664    0.500129    0.404790    0.426239   
min     18.000000   15.960000    0.000000    0.000000    0.000000    0.000000   
25%     26.000000   26.272500    0.000000    0.000000    0.000000    0.000000   
50%     38.000000   30.495000    1.000000    1.000000    0.000000    0.000000   
75%     51.000000   34.717500    2.000000    1.000000    0.000000    0.000000   
max     64.000000   53.130000    5.000000    1.000000    1.000000    1.000000   

                6           7  
count  936.000000  936.000000  
mean     0.264957    0.256410  
std      0.441546    0.436884  
min      0.000000    0.000000  
25%      0.000000    0.000000  
50%      0.000000    0.000000  
75%      1.000000    1.000000  
max      1.000000    1.000000

In [78]:
X_test_std = scaler.transform(X_test) # On test data, we reuse 
#the x_mean and x_std from the training data. 

In [79]:
from sklearn import linear_model

In [82]:
est = linear_model.LinearRegression()
est.fit(X_train_std, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [84]:
y_train_pred = est.predict(X_train_std)
y_test_pred = est.predict(X_test_std)

In [87]:
summary = pd.DataFrame({"actual": y_test, "prediction": y_test_pred})
summary["residual"] = summary.actual - summary.prediction
summary.head()

actual    prediction     residual
559    1646.4297   4610.315541 -2963.885841
1087  11353.2276  12887.893880 -1534.666280
1020   8798.5930  12573.948752 -3775.355752
460   10381.4787  13197.836626 -2816.357926
802    2103.0800    629.337182  1473.742818

In [88]:
sse = np.sum(summary.residual ** 2)
sse

14778105453.509342

In [90]:
mse = np.mean(summary.residual ** 2)
mse

36761456.35201327

In [92]:
rmse = np.sqrt(mse)
rmse

6063.122656850451

In [95]:
sse = ((y_test-y_test_pred)**2).sum()
sse

14778105453.509342

In [94]:
sst = ((y_test - np.mean(y_test)) ** 2).sum()
sst

56970102513.23878

In [96]:
sse/sst

0.25940106830727905

In [97]:
r2 = 1 - sse/sst
r2

0.740598931692721

In [101]:
from sklearn import metrics

In [105]:
print("r2 score on train", metrics.r2_score(y_train, y_train_pred))
print("r2 score on test", metrics.r2_score(y_test, y_test_pred))

print("rmse on train", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("rmse score on test", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))

r2 score on train 0.7545557492633161
r2 score on test 0.7405989316927208
rmse on train 6039.6018713245385
rmse score on test 6063.122656850453


In [108]:
pd.DataFrame({"feature": X_dummy.columns,"coefficient": est.coef_})

feature  coefficient
0               age  3528.982731
1               bmi  1961.655208
2          children   421.550164
3       gender_male  -141.359110
4        smoker_yes  9733.786883
5  region_northwest  -129.545886
6  region_southeast  -414.541483
7  region_southwest  -379.095344

In [127]:
from sklearn import *
import numpy as np

target = "charges"

y = df[target]
y = np.log(y)
X = df.drop(columns=target)
X["high_bmi"] = np.where(X.bmi > 30, "Yes", "No")
X["age_group"] = np.where(X.age > 60, "A1", "A2")

X_dummy = pd.get_dummies(X, drop_first=True)


X_train, X_test, y_train, y_test = model_selection.train_test_split(X_dummy.values, y
                                        , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=2, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LinearRegression())
])

pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("r2 score on train", metrics.r2_score(y_train, y_train_pred))
print("r2 score on test", metrics.r2_score(y_test, y_test_pred))

print("rmse on train", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("rmse score on test", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))


r2 score on train 0.8370255380513987
r2 score on test 0.8731352708297883
rmse on train 0.3714171108096169
rmse score on test 0.32667544100264784


In [121]:
a = np.array([
    [1, 1, 1],
    [-2, 3, 1],
    [4, 1, 0],
    [0, 9, 6]
])

a

array([[ 1,  1,  1],
       [-2,  3,  1],
       [ 4,  1,  0],
       [ 0,  9,  6]])

In [130]:
a = np.random.random((4, 1000))

In [131]:
poly = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
poly.fit_transform(a).shape

(4, 501500)